#!/usr/bin/env node
/**
 * Scan components/demos/<component>/<example>.tsx and generate
 * components/demos/registry.ts — a map of "<component>/<example>" keys to
 * { Component (lazy), code }. The <ComponentPreview> MDX component renders the
 * live component in one tab and the inlined source in another.
 *
 * Each demo file must `export function Demo()` (named export keeps us clear of
 * the repo's no-default-export rule; the registry adapts it for React.lazy).
 *
 * Run from apps/ui:   node scripts/build-demos.mjs
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs"
import path from "node:path"

const APP_ROOT = path.resolve(process.cwd())
const DEMOS_DIR = path.join(APP_ROOT, "components/demos")
const OUT = path.join(DEMOS_DIR, "registry.ts")

function main() {
    const entries = []
    for (const component of readdirSync(DEMOS_DIR).sort()) {
        const dir = path.join(DEMOS_DIR, component)
        if (!statSync(dir).isDirectory()) continue
        for (const file of readdirSync(dir).sort()) {
            if (!file.endsWith(".tsx")) continue
            const example = file.replace(/\.tsx$/, "")
            const key = `${component}/${example}`
            const source = readFileSync(path.join(dir, file), "utf-8").trimEnd()
            entries.push({ key, importPath: `./${component}/${example}`, code: source })
        }
    }

    const lines = [
        "// AUTO-GENERATED by scripts/build-demos.mjs — do not edit by hand.",
        '"use client"',
        "",
        'import { lazy } from "react"',
        'import type { ComponentType } from "react"',
        "",
        "export interface DemoEntry {",
        "    Component: ComponentType",
        "    code: string",
        "}",
        "",
        "export const demos: Record<string, DemoEntry> = {",
    ]
    for (const e of entries) {
        lines.push(
            `    ${JSON.stringify(e.key)}: {`,
            `        Component: lazy(() => import(${JSON.stringify(e.importPath)}).then((m) => ({ default: m.Demo }))),`,
            `        code: ${JSON.stringify(e.code)},`,
            `    },`,
        )
    }
    lines.push("}", "")

    writeFileSync(OUT, lines.join("\n"))
    console.log(`✓ ${entries.length} demos → ${OUT}`)
}

main()
